Repository SSUMC-6th/Spring_Boot_A, pull requests merged in 2024-05, with the labels that each got.

#25 [베이] Chapter 4. DATABASE 설계 & AWS RDS 설정
  docs/chapter4/Ch04keyword.md
  docs/chapter4/images/01.png
  docs/chapter4/images/02.png
  docs/chapter4/images/03.png
  docs/chapter4/images/04.png
  docs/chapter4/images/05.png
  docs/chapter4/images/06.png
  docs/chapter4/images/07.png
  docs/chapter4/images/08.png
  docs/chapter4/images/09.png
  docs/chapter4/images/10.png
  docs/chapter4/images/11.png
  docs/chapter4/images/12.png
  docs/chapter4/images/13.png
  docs/chapter4/images/14.png
  docs/chapter4/images/15.png
  docs/chapter4/images/16.png
  docs/chapter4/images/17.png
  docs/chapter4/images/18.png
  docs/chapter4/images/19.png
  src/mission/chapter4/Bey_ERD.png
  src/practice/chapter4/Bey_test_Connection.png
Labels: ✨ Chapter04

#24 [이단] Chapter 4. DATABASE 설계 & AWS RDS 설정
  docs/chapter4/Ch04Keyword.md
  src/mission/chapter4/table_diagram.png
Labels: ✨ Chapter04

#23 [바니] Chapter 4. DATABASE 설계 & AWS RDS 설정
  docs/chapter4/Ch04Keyword.md
  src/mission/chapter4/Ch04Mission.png
Labels: ✨ Chapter04

#27 [이단] Chapter05_실전 SQL - 어떤 Query를 작성해야 할까?
  src/mission/chapter5/chapter5_mission.sql
Labels: ✨ Chapter05

#28 [바니] Chapter05_실전 SQL - 어떤 Query를 작성해야 할까?
  src/mission/chapter5/Ch05Mission.sql
Labels: ✨ Chapter05

#29 [우아] Chapter 5. 실전 SQL - 어떤 Query를 작성해야 할까?
  src/mission/chapter5/1.png
  src/mission/chapter5/2.png
  src/mission/chapter5/3.png
  src/mission/chapter5/4.png
  src/mission/chapter5/Ch05Mission.md
Labels: ✨ Chapter05

#30 [베이]Chapter 5. 실전 SQL - 어떤 Query를 작성해야 할까?
  docs/chapter5/ch05keyword_01.md
  docs/chapter5/ch05keyword_02.md
  src/mission/chapter5/Bey_ERD_plus.png
  src/mission/chapter5/ch05mission_01.sql
  src/mission/chapter5/ch05mission_02.sql
  src/mission/chapter5/ch05mission_03.sql
  src/mission/chapter5/ch05mission_04.sql
Labels: ✨ Chapter05

#34 [이단] Chapter06. API URL의 설계 & 프로젝트 세팅
  src/mission/chapter6/apiSpecification.md
Labels: ✨ Chapter06

#32 [베이] Chapter06_API URL의 설계 & 프로젝트 세팅
  src/mission/chapter6/ch06mission.md
Labels: ✨ Chapter06

#39 [베이] Chapter 7. JPA를 통한 엔티티 설계, 매핑 & 프로젝트 파일 구조 이해
  docs/chapter7/ch07keyword.md
  src/mission/chapter7/ch07mission.md
  src/mission/chapter7/데이터베이스 생성.png
  src/mission/chapter7/테이블 생성.png
  src/mission/chapter7/파일 구조.png
Labels: ✨ Chapter07

#40 [이단] Chapter 7. JPA를 통한 엔티티 설계, 매핑 & 프로젝트 파일 구조 이해
  docs/chapter7/Ch07Keyword.md
  src/mission/chapter7/Ch06Mission.md
Labels: ✨ Chapter07

#38 [우아] Chapter 7. JPA를 통한 엔티티 설계, 매핑 & 프로젝트 파일 구조 이해
  docs/chapter7/Ch07Keyword.md
  src/mission/chapter7/1.png
  src/mission/chapter7/2.png
  src/mission/chapter7/3.png
  src/mission/chapter7/4.png
  src/mission/chapter7/Ch07Mission.md
Labels: ✨ Chapter07

#37 [바니] Chapter 7. JPA를 통한 엔티티 설계, 매핑 & 프로젝트 파일 구조 이해
  docs/chapter7/Ch07Keyword.md
  src/mission/chapter7/Ch07mission.png
Labels: ✨ Chapter07
